### ISSUE TITLE
Better template structure

### ISSUE THREAD

**Issue by konstantin-komelin** [50pop/nownownow.com#3]
HI Derek,

First of all, thanks for the idea of /now. I believe it really helps people to stay focused or at least remember what things they should focus on :)

I've just quickly looked through your code and noticed that you have some code duplication in the templates (/templates).

I'd like to suggest splitting up the main template into pieces, such as header, footer, etc., and than building every new template using the existing sub-templates.
An advantage: In case you need to change something in the header, for example add some additional styles, you modify code of the one template only (header.erb) and this change applies to all of the site pages.

I found some helpful info for you:
http://stackoverflow.com/a/10241263

Best,
Konstantin

**Comment by sivers** [comment]
Good point. Thank you Konstantin!
